package monitor

const (
	MsgErrIPv6ResolverTimeout            = "IPv6 resolver timeout"
	MsgErrResolverTimeout                = "resolver timeout"
	MsgErrMockDohError                   = "mock doh error"
	MsgErrMockDNSSECError                = "mock DNSSEC error"
	MsgErrResolutionFailed               = "resolution failed"
	MsgErrMockError                      = "mock error"
	MsgErrResolverErrorCNAMELoopDetected = "resolver error: CNAME loop detected"
	MsgErrTemporaryDNSFailure            = "temporary DNS failure"
	MsgErrDNSTimeout                     = "DNS timeout"
	MsgErrResolverUnavailable            = "resolver unavailable"
	MsgErrRootCause                      = "root cause"
	MsgErrCustomError                    = "custom error"
	MsgLogTestErrorMessage               = "Test error message"
	MsgLogTestWarnMessage                = "Test warn message"
	MsgLogTestInfoMessage                = "Test info message"
	MsgLogSampleLocalizedMessage         = "Sample localized message"
	MsgLogTestInfof                      = "Test infof %s"
	MsgLogTestErrorf                     = "Test errorf %s"
	MsgLogTestWarnf                      = "Test warnf %d"
	MsgLogTestDebugMessage               = "Test debug message"
	MsgLogTestDebugf                     = "Test debugf %s"
	MsgErrMockHTTPError                  = "mock http error"
	MsgErrWHOISServerNotFound            = "WHOIS server not found"
	MsgErrRDAPUnavailable                = "RDAP unavailable"
	MsgErrFirstAddressUnavailable        = "first address unavailable"
	MsgErrConnectionRefused              = "connection refused"
	MsgErrWHOISShouldNotBeQueried        = "WHOIS should not be queried"
	MsgErrMockRDAPRateLimitError         = "mock rdap rate limit error"
)
